const services = [
  [
    {
      id: 1,
      name: 'Send Money',
      icon: 'send',
      color: '#0284c7',
      bg: '#e0f2fe',
      route: "/Homescreens/Transfer",
    },
    {
      id: 2,
      name: 'Pay Bills',
      icon: 'receipt',
      color: '#16a34a',
      bg: '#dcfce7',
      route: '/bills',
    },
    {
      id: 3,
      name: 'Mobile Top-up',
      icon: 'phone-portrait',
      color: '#d97706',
      bg: '#fef3c7',
      route: '/topup',
    },
    {
      id: 4,
      name: 'International Transfers',
      icon: 'globe',
      color: '#0ea5e9',
      bg: '#e0f2fe',
      route: '/international-transfers',
    },
  ],
  [
    {
      id: 5,
      name: 'Investments',
      icon: 'trending-up',
      color: '#7c3aed',
      bg: '#f3e8ff',
      route: '/investments',
    },
    {
      id: 6,
      name: 'Loans',
      icon: 'cash',
      color: '#e11d48',
      bg: '#ffe4e6',
      route: '/loans',
    },
    {
      id: 7,
      name: 'Insurance',
      icon: 'shield-checkmark',
      color: '#0891b2',
      bg: '#cffafe',
      route: '/insurance',
    },
    {
      id: 8,
      name: 'Vouchers',
      icon: 'pricetag',
      color: '#f59e0b',
      bg: '#fef3c7',
      route: '/vouchers',
    },
  ],
  [
    {
      id: 9,
      name: 'Cards',
      icon: 'card',
      color: '#c2410c',
      bg: '#ffedd5',
      route: '/cards',
    },
    {
      id: 10,
      name: 'Savings',
      icon: 'wallet',
      color: '#4f46e5',
      bg: '#e0e7ff',
      route: '/savings',
    },
    {
      id: 11,
      name: 'Wallet Funding',
      icon: 'wallet',
      color: '#0f766e',
      bg: '#ccfbf1',
      route: '/wallet-funding',
    },
    {
      id: 12,
      name: 'Utilities',
      icon: 'flash',
      color: '#f43f5e',
      bg: '#fee2e2',
      route: '/utilities',
    },
  ],
  [
    {
      id: 13,
      name: 'Help & Support',
      icon: 'help-circle',
      color: '#3b82f6',
      bg: '#dbeafe',
      route: '/help-support',
    },
    {
      id: 14,
      name: 'Settings',
      icon: 'settings',
      color: '#6b7280',
      bg: '#f3f4f6',
      route: '/settings',
    },
    {
      id: 15,
      name: 'Notifications',
      icon: 'notifications',
      color: '#eab308',
      bg: '#fef9c3',
      route: '/notifications',
    },
    {
      id: 9,
      name: 'More',
      icon: 'grid',
      color: '#475569',
      bg: '#f1f5f9',
      route: '/Homescreens/MoreOptions',
    },
  ],
];

export default services;
